<?php

namespace ContainerTfROMBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UEKGlEUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UEKGlEU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UEKGlEU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PanierController::add' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PanierController::getPanier' => ['privates', '.service_locator.fBpndJA', 'get_ServiceLocator_FBpndJAService', true],
            'App\\Controller\\PanierController::removeFromCart' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PaymentController::finalizePayment' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\PaymentController::testSendEmail' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.JM5nZSk', 'get_ServiceLocator_JM5nZSkService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.1GMkKNd', 'get_ServiceLocator_1GMkKNdService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.iD_O4kk', 'get_ServiceLocator_IDO4kkService', true],
            'App\\Controller\\UserController::editUser' => ['privates', '.service_locator.GGMyS3j', 'get_ServiceLocator_GGMyS3jService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\PanierController:add' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PanierController:getPanier' => ['privates', '.service_locator.fBpndJA', 'get_ServiceLocator_FBpndJAService', true],
            'App\\Controller\\PanierController:removeFromCart' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PaymentController:finalizePayment' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\PaymentController:testSendEmail' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.JM5nZSk', 'get_ServiceLocator_JM5nZSkService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ZJzZ1Z2', 'get_ServiceLocator_ZJzZ1Z2Service', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.M9PMcRV', 'get_ServiceLocator_M9PMcRVService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.1GMkKNd', 'get_ServiceLocator_1GMkKNdService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.iD_O4kk', 'get_ServiceLocator_IDO4kkService', true],
            'App\\Controller\\UserController:editUser' => ['privates', '.service_locator.GGMyS3j', 'get_ServiceLocator_GGMyS3jService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\PanierController::add' => '?',
            'App\\Controller\\PanierController::getPanier' => '?',
            'App\\Controller\\PanierController::removeFromCart' => '?',
            'App\\Controller\\PaymentController::finalizePayment' => '?',
            'App\\Controller\\PaymentController::testSendEmail' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::editUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PanierController:add' => '?',
            'App\\Controller\\PanierController:getPanier' => '?',
            'App\\Controller\\PanierController:removeFromCart' => '?',
            'App\\Controller\\PaymentController:finalizePayment' => '?',
            'App\\Controller\\PaymentController:testSendEmail' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:editUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
