<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfROMBB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfROMBB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTfROMBB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTfROMBB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTfROMBB\App_KernelDevDebugContainer([
    'container.build_hash' => 'TfROMBB',
    'container.build_id' => '38793e7c',
    'container.build_time' => 1712138989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfROMBB');
