<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'panier_add' => [[], ['_controller' => 'App\\Controller\\PanierController::add'], [], [['text', '/api/panier/add']], [], [], []],
    'get_panier' => [[], ['_controller' => 'App\\Controller\\PanierController::getPanier'], [], [['text', '/api/panier']], [], [], []],
    'panier_remove' => [['produitId'], ['_controller' => 'App\\Controller\\PanierController::removeFromCart'], [], [['variable', '/', '[^/]++', 'produitId', true], ['text', '/api/panier/remove']], [], [], []],
    'finalize_payment' => [[], ['_controller' => 'App\\Controller\\PaymentController::finalizePayment'], [], [['text', '/finalize-payment']], [], [], []],
    'email' => [[], ['_controller' => 'App\\Controller\\PaymentController::testSendEmail'], [], [['text', '/email']], [], [], []],
    'produit_index' => [[], ['_controller' => 'App\\Controller\\ProduitController::index'], [], [['text', '/api/produits/']], [], [], []],
    'produit_new' => [[], ['_controller' => 'App\\Controller\\ProduitController::new'], [], [['text', '/api/produits/new']], [], [], []],
    'produit_edit' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/produits']], [], [], []],
    'produit_delete' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/produitsdelete']], [], [], []],
    'produit_show' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/produits']], [], [], []],
    'produits_by_category' => [['categoryId'], ['_controller' => 'App\\Controller\\ProduitController::getProductsByCategory'], [], [['variable', '/', '[^/]++', 'categoryId', true], ['text', '/api/produits/api/produits/category']], [], [], []],
    'api_profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/api/profile']], [], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/register']], [], [], []],
    'edit_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::editUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/utilisateurs/edit']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/utilisateurs/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
